name: Update VERSION on Release
on:
  push:
    tags:
      - 'v*'
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update VERSION
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "${TAG#v}" > VERSION
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add VERSION
          git commit -m "Update VERSION to ${TAG#v}"
          git push origin main
